---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
stringData:
  database-password: {{ .Values.databasePassword }}
  database-user: {{ .Values.databaseUser }}
{{- if .Values.postgresqlCA }}
  postgresql-ca.pem: |
{{ .Values.postgresqlCA | indent 4 }}
{{- end }}
