kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:{{ template "exoscale-cloud-controller-manager.fullname" . }}
  labels:
    app: {{ template "exoscale-cloud-controller-manager.name" . }}
    chart: {{ template "exoscale-cloud-controller-manager.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
subjects:
- kind: ServiceAccount
  name: {{ template "exoscale-cloud-controller-manager.fullname" . }}
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: system:{{ template "exoscale-cloud-controller-manager.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
