kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:{{ template "exoscale-cloud-controller-manager.fullname" . }}
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    app: {{ template "exoscale-cloud-controller-manager.name" . }}
    chart: {{ template "exoscale-cloud-controller-manager.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "*"
