apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "exoscale-cloud-controller-manager.fullname" . }}
  labels:
{{ include "exoscale-cloud-controller-manager.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "exoscale-cloud-controller-manager.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "exoscale-cloud-controller-manager.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      dnsPolicy: Default
      hostNetwork: true
      serviceAccountName: {{ template "exoscale-cloud-controller-manager.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
{{- if .Values.containers }}
{{ toYaml .Values.containers | indent 8 }}
{{- end }}
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --cloud-provider=exoscale
            - --leader-elect=true
            - --allow-untagged-cloud
          env:
            - name: EXOSCALE_API_KEY
              valueFrom:
                secretKeyRef:
                  key: api_key
                  name: {{ include "exoscale-cloud-controller-manager.fullname" . }}-credentials
            - name: EXOSCALE_API_SECRET
              valueFrom:
                secretKeyRef:
                  key: api_secret
                  name: {{ include "exoscale-cloud-controller-manager.fullname" . }}-credentials
            - name: EXOSCALE_API_ENDPOINT
              valueFrom:
                secretKeyRef:
                  key: api_endpoint
                  name: {{ include "exoscale-cloud-controller-manager.fullname" . }}-credentials
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
