---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "exoscale-cloud-controller-manager.fullname" . }}-credentials
  labels:
{{ include "exoscale-cloud-controller-manager.labels" . | indent 4 }}
stringData:
  api_key: {{ .Values.exoscale.api_key | quote }}
  api_secret: {{ .Values.exoscale.api_secret | quote }}
  api_endpoint: {{ .Values.exoscale.api_endpoint | quote }}
