{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "exoscale-cloud-controller-manager.serviceAccountName" . }}
  labels:
{{ include "exoscale-cloud-controller-manager.labels" . | indent 4 }}
{{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- end -}}
