apiVersion: v1
kind: Service
metadata:
  name: {{ template "external-service.fullname" . }}
  labels:
    app: {{ template "external-service.name" . }}
    chart: {{ template "external-service.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetport }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector: {}
