apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "prometheus-puppetdb.fullname" . }}
  labels:
    app: {{ template "prometheus-puppetdb.name" . }}
    chart: {{ template "prometheus-puppetdb.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "prometheus-puppetdb.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "prometheus-puppetdb.name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ template "prometheus-puppetdb.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
        {{- if .Values.prometheusPuppetdb.args }}
          {{- if not .Values.prometheusPuppetdb.args.output }}
            - --output=external-services
          {{- end }}
          {{- range $key, $value := .Values.prometheusPuppetdb.args }}
            - --{{ $key }}={{ $value }}
          {{- end }}
        {{- else }}
            - --output=external-services
        {{- end }}
        {{- if .Values.prometheusPuppetdb.env }}
          env:
{{ toYaml .Values.prometheusPuppetdb.env | indent 12 }}
        {{- end }}
        {{- if and .Values.CACert .Values.Cert .Values.Key }}
          volumeMounts:
          - name: certs
            mountPath: /certs
            readOnly: true
        {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- if and .Values.CACert .Values.Cert .Values.Key }}
      volumes:
      - name: certs
        secret:
          secretName: {{ template "prometheus-puppetdb.fullname" . }}
    {{- end }}
