{{- if and .Values.CACert .Values.Cert .Values.Key }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "prometheus-puppetdb.fullname" . }}
  labels:
    app: {{ template "prometheus-puppetdb.name" . }}
    chart: {{ template "prometheus-puppetdb.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  cacert.pem: {{ .Values.CACert | b64enc }}
  client.pem: {{ .Values.Cert | b64enc }}
  client.key: {{ .Values.Key | b64enc }}
{{- end }}
