# Default values for ruby-ex.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
api_version: openshift.org/v1

source:
  git:
    uri: https://github.com/openshift/ruby-ex.git  

build:
  from:
    repository: centos/ruby-22-centos7
    tag: latest

service:
  port: 8080
  protocol: TCP
  targetPort: 8080
