# Default values for blackbox-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## Container image
##
image:
  repository: prom/blackbox-exporter
  tag: v0.12.0
  pullPolicy: IfNotPresent


## Custom update strategy
##
updateStrategy:
  type: OnDelete


## Additional blackbox-exporter container arguments
##
extraArgs: {}


## Node labels for pod assigment
##
nodeSelector: {}


## Annotations to be added to the pod
##
podAnnotations: {}


##
##
service:
  annotations: {}
  labels: {}

  servicePort: 9115


## Configuration file
##
configFiles:
  config.yml:
    modules:
      http_2xx:
        prober: http
        timeout: 5s
        http:
