---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app: {{ template "name" . }}
spec:
  replicas: 1
  strategy:
    resources: {}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: useroot
      containers:
        - env:
            - name: AUTOSIGN_PSK
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: autosign-psk
{{- if .Values.caCrt }}
            - name: CA_CRT
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: ca-crt
{{- end }}
{{- if .Values.caKey }}
            - name: CA_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: ca-key
{{- end }}
            - name: DNS_ALT_NAMES
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: dns-alt-names
{{- if .Values.gpgKey }}
            - name: GPG_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: gpg-key
{{- end }}
            - name: JAVA_ARGS
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: java_args
          name: puppet
          image: {{ .Values.image }}:{{ .Values.imageTag }}
          imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
          resources: {}
          volumeMounts:
            - name: puppetcode
              mountPath: /etc/puppetlabs/code
            - name: puppetca
              mountPath: /etc/puppetlabs/puppet/ssl/ca
      restartPolicy: Always
      volumes:
        - name: puppetcode
          persistentVolumeClaim:
            claimName: {{ template "fullname" . }}-puppetcode
        - name: puppetca
          persistentVolumeClaim:
            claimName: {{ template "fullname" . }}-puppetca
