---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "fullname" . }}-puppetca
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app: {{ template "name" . }}
spec:
  accessModes:
    - {{ .Values.persistence.puppetca.accessMode | quote }}
  resources:
    requests:
      storage: 100Mi
{{- if .Values.persistence.puppetca.storageClass }}
{{- if (eq "-" .Values.persistence.puppetca.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.puppetca.storageClass }}"
{{- end }}
{{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "fullname" . }}-puppetcode
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app: {{ template "name" . }}
spec:
  accessModes:
    - {{ .Values.persistence.puppetcode.accessMode | quote }}
  resources:
    requests:
      storage: 10Gi
{{- if .Values.persistence.puppetcode.storageClass }}
{{- if (eq "-" .Values.persistence.puppetcode.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.puppetcode.storageClass }}"
{{- end }}
{{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "fullname" . }}-r10kcache
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app: {{ template "name" . }}
spec:
  accessModes:
    - {{ .Values.persistence.r10kcache.accessMode | quote }}
  resources:
    requests:
      storage: 500Mi
{{- if .Values.persistence.r10kcache.storageClass }}
{{- if (eq "-" .Values.persistence.r10kcache.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.r10kcache.storageClass }}"
{{- end }}
{{- end }}
