kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "bivac.fullname" . }}
  labels:
    app: {{ template "bivac.name" . }}
    chart: {{ template "bivac.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
subjects:
- kind: ServiceAccount
  name: {{ template "bivac.fullname" . }}
  namespace: cluster-backup
roleRef:
  kind: ClusterRole
  name: {{ template "bivac.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
