---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "puppetserver.fullname" . }}-user-confdir
  labels:
    app.kubernetes.io/name: {{ include "puppetserver.name" . }}
    helm.sh/chart: {{ include "puppetserver.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  puppet.conf: |
    [main]
    ssldir = /etc/puppetlabs/puppet/ssl
    server = {{ include "puppetserver.fullname" . }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "puppetserver.fullname" . }}-puppetserver
  labels:
    app.kubernetes.io/name: {{ include "puppetserver.name" . }}
    helm.sh/chart: {{ include "puppetserver.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  ca.conf: |
{{ .Values.ca_conf | indent 4 }}
  auth.conf: |
{{ .Values.auth_conf | indent 4 }}
  metrics.conf: |
    # settings related to metrics
    metrics: {
        # a server id that will be used as part of the namespace for metrics produced
        # by this server
        server-id: localhost
        registries: {
            puppetserver: {
                # specify metrics to allow in addition to those in the default list
                #metrics-allowed: ["compiler.compile.production"]

                reporters: {
                    # enable or disable JMX metrics reporter
                    jmx: {
                        enabled: true
                    }
                    # enable or disable Graphite metrics reporter
                    graphite: {
                        enabled: true
                    }
                }

            }
        }

        # this section is used to configure settings for reporters that will send
        # the metrics to various destinations for external viewing
        reporters: {
            graphite: {
                # graphite host
                host: "127.0.0.1"
                # graphite metrics port
                port: 9109
                # how often to send metrics to graphite
                update-interval-seconds: 5
            }
        }
        metrics-webservice: {
            jolokia: {
                # Enable or disable the Jolokia-based metrics/v2 endpoint.
                # Default is true.
                # enabled: false

                # Configure any of the settings listed at:
                #   https://jolokia.org/reference/html/agents.html#war-agent-installation
                servlet-init-params: {
                    # Specify a custom security policy:
                    #  https://jolokia.org/reference/html/security.html
                    # policyLocation: "file:///etc/puppetlabs/puppetserver/jolokia-access.xml"
                }
            }
        }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "puppetserver.fullname" . }}-puppet
  labels:
    app.kubernetes.io/name: {{ include "puppetserver.name" . }}
    helm.sh/chart: {{ include "puppetserver.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  puppet.conf: |
{{ .Values.puppet_conf | indent 4 }}
  hiera.yaml: |
    ---
    version: 5
  autosign: |
{{ .Values.autosign.script | indent 4 }}
  puppetdb.conf: |
{{ .Values.puppetdb_conf | indent 4 }}
  routes.yaml: |
{{ .Values.routes_yaml | indent 4 }}
