apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "puppetserver.name" . }}
  labels:
    {{- include "puppetserver.release_labels" . | indent 4 }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "puppetserver.release_labels" . | indent 8 }}
    spec:
      containers:
      - name: puppetserver
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - mountPath: /run/secrets/ca_key.pem
          name: secrets
          subPath: ca_key.pem
          readOnly: true
        - mountPath: /run/secrets/ca_crt.pem
          name: secrets
          subPath: ca_crt.pem
          readOnly: true
        - mountPath: /run/secrets/ca_crl.pem
          name: secrets
          subPath: ca_crl.pem
          readOnly: true
        - mountPath: /run/secrets/gpg.asc
          name: secrets
          subPath: gpg.asc
          readOnly: true
        - mountPath: /run/secrets/autosign_psk
          name: secrets
          subPath: autosign_psk
          readOnly: true

      - name: g10k-webhook
        image: camptocamp/g10k-webhook:latest
        env:
        - name: HOOK_SECRET
          value: "SeCr3t"
        volumeMounts:
        - mountPath: /run/secrets/id_rsa
          name: secrets
          subPath: id_rsa
          readOnly: true
        - mountPath: /etc/puppetlabs/code
          name: puppetcode

      volumes:
      - name: secrets
        secret:
          secretName: secrets
      - name: puppetcode
        emptyDir: {}
