{{- if .Values.autoScaling.enabled }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "puppetserver.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "puppetserver.name" . }}
    helm.sh/chart: {{ include "puppetserver.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "puppetserver.fullname" . }}
  minReplicas: {{ .Values.autoScaling.minCompilers }}
  maxReplicas: {{ .Values.autoScaling.maxCompilers }}
  metrics:
{{- with .Values.autoScaling.cpuUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ . }}
{{- end }}
{{- with .Values.autoScaling.memoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ . }}
{{- end }}
{{- end }}
