apiVersion: v1
kind: Secret
metadata:
  name: {{ include "puppetserver.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "puppetserver.name" . }}
    helm.sh/chart: {{ include "puppetserver.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
stringData:
  ca_key.pem: |-
{{ .Values.ca.key | indent 4 }}
  ca_crt.pem: |-
{{ .Values.ca.crt | indent 4 }}
  ca_crl.pem: |-
{{ .Values.ca.crl | indent 4 }}
  gpg.asc: |-
{{ .Values.gpg| indent 4 }}
  autosign_psk: |-
{{ .Values.ca.autosign.psk | indent 4 }}
