dependencies:
- name: logstash
  version: "7.5.1"
  repository: "https://helm.elastic.co"
- name: elasticsearch-curator
  version: "2.1.3"
  repository: "https://kubernetes-charts.storage.googleapis.com/"
