---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app: {{ template "name" . }}
stringData:
  githubToken: {{ .Values.githubToken }}
  hooksSecret: {{ .Values.hooksSecret }}
  id_rsa: |
{{ .Values.idRsa | indent 4 }}
