---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app: {{ template "name" . }}
spec:
  ports:
    - name: r10k-webhook
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
