{{- if .Values.additionalYamlConfig }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "terraboard.fullname" . }}-configmap
  labels:
{{ include "terraboard.labels" . | indent 4 }}
data:
  config.yaml: {{ .Values.additionalYamlConfig | indent 4 }}
{{- end }}