---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "terraboard.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "terraboard.name" . }}
    helm.sh/chart: {{ include "terraboard.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
stringData:
  aws_access_key_id: {{ .Values.aws.accessKeyId }}
  aws_secret_access_key: {{ .Values.aws.secretAccessKey }}
  db_password: {{ .Values.db.password }}
