---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "terraboard.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "terraboard.name" . }}
    helm.sh/chart: {{ include "terraboard.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.aws.key_id | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws.secret_access_key | quote }}
  DB_USER: {{ .Values.db.user | quote }}
  DB_PASSWORD: {{ .Values.db.password | quote }}
