apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "terraboard.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "terraboard.name" . }}
    helm.sh/chart: {{ include "terraboard.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"terraboard"}}'
