apiVersion: v1
kind: Service
metadata:
  name: {{ include "terraboard.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "terraboard.name" . }}
    helm.sh/chart: {{ include "terraboard.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: {{ include "terraboard.name" . }}-proxy-tls
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: public
      protocol: TCP
      name: proxy
  selector:
    app.kubernetes.io/name: {{ include "terraboard.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
