---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus-postgres-exporter.fullname" . }}-master
  labels:
{{ include "prometheus-postgres-exporter.labels" . | indent 4 }}
data:
  queries.yaml: |-
    {{- tpl (.Files.Get "prometheus-exporter-queries.yaml") (merge (dict "role" "master") $) | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus-postgres-exporter.fullname" . }}-replica
  labels:
{{ include "prometheus-postgres-exporter.labels" . | indent 4 }}
data:
  queries.yaml: |-
    {{- tpl (.Files.Get "prometheus-exporter-queries.yaml") (merge (dict "role" "replica") $) | nindent 4 }}
