{{- $config := dict "version" .Values.version "role" "master" "pg_stat_statements" .Values.pg_stat_statements }}
{{- $_ := set $ "version" .Values.version }}
{{- $_ := set $ "role" (dict "type" "master") }}
{{- $_ := set $ "pg_stat_statements" .Values.pg_stat_statements }}
{{- $_ := set $ "rds" .Values.rds }}
{{- $_ := set $ "pg_stat_user_tables" .Values.pg_stat_user_tables }}
{{- $_ := set $ "light_threshold" .Values.light_threshold }}
{{- $_ := set $ "pg_client_connections" .Values.pg_client_connections }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-master
  labels:
{{ include "prometheus-postgres-exporter.labels" . | indent 4 }}
data:
  queries.yaml: |-
    {{- tpl (.Files.Get "prometheus-exporter-queries.yaml") $ | nindent 4 }}
{{- $_ := set $ "role" (dict "type" "replica") }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-replica
  labels:
{{ include "prometheus-postgres-exporter.labels" . | indent 4 }}
data:
  queries.yaml: |-
    {{- tpl (.Files.Get "prometheus-exporter-queries.yaml") $ | nindent 4 }}
