apiVersion: v1
kind: Secret
metadata:
  name: jenkins-secrets
  labels:
    "credential.sync.jenkins.openshift.io": "true"
{{ include "common.labels.standard" . | indent 4 }}
data:
  gitlabToken: {{ .Values.gitlabConnection.apiToken | b64enc }}
