apiVersion: v1
kind: Secret
type: kubernetes.io/ssh-auth
metadata:
  name: {{ .Values.sshSecretName }}
  labels:
{{ include "common.labels.standard" . | indent 4 }}
data:
  ssh-privatekey: {{ .Values.sshPrivateKey | b64enc }}