apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.jenkins_service_name | quote }}
  label:
{{ include "common.labels.standard" . | indent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volume_capacity | quote }}