apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: {{ .Values.jnlp_service_name | quote }}
  label:
{{ include "common.labels.standard" . | indent 4 }}
  spec:
    ports:
    - name: agent
      nodePort: 0
      port: 50000
      protocol: TCP
      targetPort: 50000
    selector:
      name: {{ .Values.jenkins_service_name | quote }}
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      service.alpha.openshift.io/dependencies: '[{"name": "{{ .Values.jnlp_service_name }}",
        "namespace": "", "kind": "Service"}]'
      service.openshift.io/infrastructure: "true"
    name: {{ .Values.jenkins_service_name | quote }}
  label:
{{ include "common.labels.standard" . | indent 4 }}
  spec:
    ports:
    - name: web
      nodePort: 0
      port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      name: {{ .Values.jenkins_service_name | quote }}
    sessionAffinity: None
    type: ClusterIP
kind: List