{{ $root := . }}
apiVersion: v1
items:
{{- range $key, $value := .Values.jenkins_slaves }}
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
{{ include "common.labels.standard" $root | indent 6 }}
    name: "jenkins-slave-{{ $key }}"
  spec:
    lookupPolicy:
      local: false
    tags:
    - from:
        kind: DockerImage
        name: "{{ $root.Values.image.registry }}/{{ $root.Values.image.org }}/jenkins-slave-{{ $key }}:latest"
      name: latest
      importPolicy:
        scheduled: true{{- end }}
kind: List

