{{ $root := . }}
apiVersion: v1
items:
{{- range $key, $value := .Values.jenkins_slaves }}
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
{{ include "common.labels.standard" $root | indent 6 }}
      build: "jenkins-slave-{{ $key }}"
    name: "jenkins-slave-{{ $key }}"
  spec:
    nodeSelector: null
    output:
      to:
        kind: DockerImage
        name: "{{ $root.Values.image.registry }}/jenkins-slave-{{ $key }}:latest"
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: {{ $value.repository.context_dir | quote }}
      git:
        uri: {{ $value.repository.url | quote }}
        ref: {{ $value.repository.ref | quote }}
      sourceSecret:
        name: {{ $root.Values.sshSecretName | quote }}
      type: Git
    strategy:
      type: Docker
    successfulBuildsHistoryLimit: 5
    triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
{{- end }}
kind: List
