apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  generateName: {{ include "prometheus.fullname" . }}-
  labels:
{{ include "prometheus.labels" . | indent 4 }}
spec:
  source: rh-operators
  name: prometheus
  startingCSV: prometheusoperator.0.22.2
  channel: preview
