apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    preferredChain: ''
    privateKeySecretRef:
      name: letsencrypt-prod-key
    server: 'https://acme-v02.api.letsencrypt.org/directory'
    solvers:
      - selector:
          dnsZones:
           - {{ index .Values "cert-manager" "dnsZone" | quote }}
        dns01:
          route53:
            region: eu-west-1
            accessKeyID: {{ index .Values "cert-manager" "accessKey" }}
            secretAccessKeySecretRef:
              name: prod-route53-credentials-secret
              key: secret-access-key
