apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: {{ include "gitlab-backup.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "gitlab-backup.name" . }}
    helm.sh/chart: {{ include "gitlab-backup.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  output:
    to:
      kind: "ImageStreamTag"
      name: "docker-gitlab-openshift-backup:latest"
  source:
    type: "Git"
    git:
      uri: "https://github.com/camptocamp/docker-gitlab-openshift-backup"
  strategy:
    sourceStrategy:
      from:
        kind: "ImageStreamTag"
        name: "builder-image:latest"
      forcePull: true
  triggers:
    - type: "imageChange"
      imageChange: {}
    - type: "Github"
      github:
        secretReference:
          name: {{ include "gitlab-backup.fullname" . }}