apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: {{ include "gitlab-backup.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "gitlab-backup.name" . }}
    helm.sh/chart: {{ include "gitlab-backup.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  output:
    to:
      kind: "ImageStreamTag"
      name: "{{ include "gitlab-backup.fullname" . }}:latest"
  source:
    type: "Git"
    git:
      uri: "https://github.com/camptocamp/docker-gitlab-openshift-backup"
  strategy:
    dockerStrategy: {}
  triggers:
    - type: "GitHub"
      github:
        secretReference:
          name: {{ include "gitlab-backup.fullname" . }}
    - type: "ConfigChange"
{{- if .Values.buildconfig.resources }}
  resources:
{{ toYaml .Values.buildconfig.resources | indent 4 }}
{{ end }}
