apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: gitlab-backup-cron
spec:
  # run every day
  schedule: {{ .Values.schedule | quote}} 
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: gitlab-backup-cron
          containers:
          - name: gitlab-backup-cron-oc-client
            image: docker-registry.default.svc:5000/gitlab/gitlab-backup:latest
            args:
            - /usr/sbin/gitlab-backup.sh -s={{.Values.sre_team}} {{ if .Values.prometheus_pushgateway_url }} -p={{.Values.prometheus_pushgateway_url }} {{end}}
          restartPolicy: Never
