apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  generation: 1
  labels:
    app: gitlabackup
  name: gitlab-backup
  selfLink: /apis/apps.openshift.io/v1/namespaces/myproject/deploymentconfigs/openshift-client
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: openshift-client
      deploymentconfig: openshift-client
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: openshift-client
        deploymentconfig: openshift-client
    spec:
      containers:
      - image: ebits/openshift-client@sha256:31c5e7dba9ea7987c55b1ff7b7e6ad6f35d4eb6124dfbb86b66024104f7b60ff
        imagePullPolicy: Always
        name: openshift-client
        ports:
        - containerPort: 8001
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        args:
        - /bin/sh
        - -c
        - while sleep 3600; do :; done
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      serviceAccountName: gitlab-backup-cron
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - openshift-client
      from:
        kind: ImageStreamTag
        name: openshift-client:latest
        namespace: myproject
    type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
