apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: gitlab-backup-pod-executor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-executor
subjects:
  - kind: ServiceAccount
    name: gitlab-backup-cron
