---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gitlab-backup.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "gitlab-backup.name" . }}
    helm.sh/chart: {{ include "gitlab-backup.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
stringData:
  WebHookSecretKey: {{ .Values.webhook.secret }}
