apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
{{ include "common.labels.standard" . | indent 4 }}
  name: nexus3
spec:
  replicas: 1
  selector:
    app: nexus3
    deploymentconfig: nexus3
  strategy:
    resources: {}
    type: Rolling
  template:
    metadata:
      labels:
        app: nexus3
        deploymentconfig: nexus3
    spec:
      containers:
      - image: sonatype/nexus3
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - echo
            - ok
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: nexus3
        ports:
        - containerPort: 8081
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /nexus-data
          name: nexus3-volume-1
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: nexus3-volume-1
        persistentVolumeClaim:
          claimName: nexus3-pv
  test: false
  triggers:
  - type: ConfigChange
