apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
{{ include "common.labels.standard" . | indent 4 }}
  name: nexus3-pv
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
