replicaCount: 1

namespaceOverride: ""

containerPort: 8080

serverRoot: "/etc/httpd/conf.d"
serverConfig: "/etc/httpd/conf/httpd.conf"

securityContext:
  runAsUser: 1000
logcleanup:
  enabled: false
backup:
  enabled: false
  # THe following are only needed if backup is enabled
  # databaseurl: some.mysql.url
  # s3endpoint: 'https://some.s3endpoint.url'
  # s3bucket: 'Bucket name'

monitoring:
  enabled: false
  image:
    repository: lusotycoon/apache-exporter
    tag: v0.8.0
    pullPolicy: IfNotPresent
  portNumber: '9117'

image:
  repository: httpd
  tag: 2.4-alpine
  pullPolicy: IfNotPresent

storage:
  pvName: ""

apache:
  config: ""
  remoteips: ""
  user: ""

# tls:

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
