---
apiVersion: v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app: {{ template "name" . }}
spec:
  replicas: 1
  strategy:
    resources: {}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: useroot
      containers:
        - env:
            - name: AUTOSIGN_PSK
              valueFrom:
                secretKeyRef:
                  name: puppet-puppetserver
                  key: autosign-psk
            - name: DNS_ALT_NAMES
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: dns-alt-names
            - name: ENABLE_HTTP
              value: "true"
            - name: JAVA_ARGS
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: java_args
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: database-password
            - name: POSTGRES_SUBNAME
              value: //192.168.1.14:5432/puppetdb?ssl=true&sslfactory=org.postgresql.ssl.jdbc4.LibPQFactory&sslmode=verify-full&sslrootcert=/etc/puppetlabs/puppetdb/ssl-postgresql/postgresql-ca.pem
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: database-user
          image: camptocamp/puppetdb:5.1.4-0.3
          name: puppetdb
          resources: {}
          volumeMounts:
            - name: postgresqlca
              mountPath: /etc/puppetlabs/puppetdb/ssl-postgresql
      restartPolicy: Always
      volumes:
        - name: postgresqlca
          secret:
            secretName: {{ template "fullname" . }}
