apiVersion: v1
kind: ConfigMap
metadata:
  name: conf-d
data:
  database.ini: |-
    [database]
    subname = {{ .Values.postgres_subname  }}
    username = {{ .Values.postgres_user }}
    password = {{ .Values.postgres_password }}
{{- if .Values.postgres_ro_subname }}
    [read-database]
    subname = {{ .Values.postgres_ro_subname }}
    username = {{ .Values.postgres_ro_user }}
    password = {{ .Values.postgres_ro_password }}
{{- end }}
  jetty.ini: |-
    [jetty]
    port = 8080
    host = 0.0.0.0
    ssl-port=8081
    ssl-host=0.0.0.0
    ssl-key=/run/secrets/private.pem
    ssl-cert=/run/secrets/public.pem
    ssl-ca-cert=/run/secrets/ca.pem
