apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "puppetdb.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "puppetdb.name" . }}
    helm.sh/chart: {{ include "puppetdb.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "puppetdb.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "puppetdb.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          volumeMounts:
          - mountPath: /etc/puppetlabs/puppetdb/conf.d/
            name: conf-d
            readOnly: true
          - mountPath: /etc/puppetlabs/puppet/ssl/private_keys/puppetdb.pem
            name: ssl
            subPath: private.pem
            readOnly: true
          - mountPath: /etc/puppetlabs/puppet/ssl/certs/puppetdb.pem
            name: ssl
            subPath: public.pem
            readOnly: true
          - mountPath: /etc/puppetlabs/puppet/ssl/certs/ca.pem
            name: ssl
            subPath: ca.pem
            readOnly: true
#          livenessProbe:
#            httpGet:
#              path: /
#              port: http
#          readinessProbe:
#            httpGet:
#              path: /
#              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: ssl
          secret:
            secretName: {{ include "puppetdb.fullname" . }}
        - name: conf-d
          configMap:
            name: {{ include "puppetdb.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
