---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "puppetdb.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "puppetdb.name" . }}
    helm.sh/chart: {{ include "puppetdb.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
stringData:
  private.pem: |-
{{ .Values.private_pem | indent 4 }}
  public.pem: |-
{{ .Values.public_pem | indent 4 }}
  ca.pem: |-
{{ .Values.ca_pem | indent 4 }}
