---
apiVersion: v1
kind: Secret
metadata:
  name: ssl-files
  labels:
    {{- include "puppetdb.release_labels" . | indent 4 }}
stringData:
  private.pem: |-
{{ .Values.private_pem | indent 4 }}
  public.pem: |-
{{ .Values.public_pem | indent 4 }}
  ca.pem: |-
{{ .Values.ca_pem | indent 4 }}
