apiVersion: v1
kind: Service
metadata:
  name: {{ template "puppetdb.name" . }}
  labels:
    {{- include "puppetdb.release_labels" . | indent 4 }}
spec:
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
  selector:
    app: {{ template "puppetdb.name" . }}
