apiVersion: v1
kind: Service
metadata:
  name: {{ include "puppetdb.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "puppetdb.name" . }}
    helm.sh/chart: {{ include "puppetdb.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{ if .Values.prometheusPuppetDBExporter.enabled }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.prometheusPuppetDBExporter.service.port }}"
{{ end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
{{ if .Values.prometheusPuppetDBExporter.enabled }}
    - port: {{ .Values.prometheusPuppetDBExporter.service.port }}
      targetPort: puppetdb-exp
      protocol: TCP
      name: puppetdb-exp
{{ end }}

  selector:
    app.kubernetes.io/name: {{ include "puppetdb.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
