---
apiVersion: v1
kind: Secret
type: {{ .Values.type }}
metadata:
  name: {{ .Values.name }}
  labels:
{{ include "common.labels.standard" . | indent 4 }}
{{ with .Values.annotations }}
  annotations:
{{  toYaml . | indent 4 }}
{{- end }}
data:
{{- range $data := .Values.data }}
  {{ $data.key }}: {{ $data.value | b64enc }}
{{- end }}