---
apiVersion: v1
kind: Secret
type: {{ .Values.type }}
metadata:
  name: {{ .Values.name }}
  labels:
{{      include "common.labels.standard" . | indent 4 }}
data:
{{- range $data := .Values.data }}
  {{ $data.key }}: {{ $data.value | b64enc }}
{{- end }}