{{- if .Values.isOpenshift }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "oauth2-proxy.fullname" . }}
  annotations:
    serviceaccounts.openshift.io/oauth-redirecturi.primary: "{{- range $host := .Values.ingress.hosts -}}https://{{ $host }},{{- end -}}"
{{- end }}
