apiVersion: v1
kind: Service
metadata:
  name: {{ template "ruby-ex.fullname" . }}
  labels:
    {{- include "ruby-ex.release_labels" . | indent 4 }}
spec:
  ports:
  - name: {{ .Values.service.port }}-{{ .Values.service.protocol }}
    port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol }}
    targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ template "ruby-ex.fullname" . }}
    deploymentconfig: {{ template "ruby-ex.fullname" . }}
