image:
  repository: camptocamp/pghoard
  tag: "10"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 16000

persistentVolume:
  enabled: false
  accessModes:
    - ReadWriteOnce
  size: 100Mi
