apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
{{ include "bivac.labels" . | indent 4 }}
    {{- if .Values.metrics.serviceMonitor.additionalLabels }}
{{ toYaml .Values.metrics.serviceMonitor.additionalLabels | indent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: api
      port: {{ .Values.service.port }}
      targetPort: api
  selector:
    app: {{ template "bivac.name" . }}
    release: {{ .Release.Name }}
