apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: {{ .Values.name }}
  labels:
{{  include "common.labels.standard" . | indent 4 }}
{{- with .Values.scc }}
{{    toYaml . }}
{{- end }}
