image:
  repository: camptocamp/puppetdb
  tag: 'arbitrary_user'
  pullPolicy: IfNotPresent

dns_alt_names: 'puppetdb'
java_args: ''
postgres_subname: '//postgres:5432/puppetdb'
postgres_user: 'puppetdb'
postgres_password: 'puppetdb'
postgres_ro_subname: ''
postgres_ro_user: 'puppetdb'
postgres_ro_password: 'puppetdb'

private_pem: ''
public_pem: ''
ca_pem: ''
