image:
  repository: camptocamp/puppetdb
  tag: '5.2.0-0.2'

dns_alt_names: 'puppetdb'
java_args: ''
postgres_subname: '//postgres:5432/puppetdb'
postgres_user: 'puppetdb'
postgres_password: 'puppetdb'
postgres_ro_subname: ''
postgres_ro_user: 'puppetdb'
postgres_ro_password: 'puppetdb'
