apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "chart.fullname" . }}-config
  labels:
    app: {{ template "chart.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  config.yml: |
{{ .Values.config | indent 4 }}
