apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  labels:
{{ include "haproxy-postgres.labels" . | indent 4 }}
data:
  haproxy.cfg: |
    {{- tpl (.Files.Get "haproxy.cfg") . | nindent 4 }}
