{{- if .Values.metrics.enabled }}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-prometheus-exporter
  labels:
{{ include "haproxy-postgres.labels" . | indent 4 }}
spec:
  template:
    metadata:
      labels:
        component: exporter
{{ include "haproxy-postgres.selector" . | indent 8 }}
      annotations:
        prometheus.io/port: '9101'
        prometheus.io/scrape: 'true'
    spec:
      containers:
        - name: haproxy
          image: {{ .Values.prometheusExporterImage.repository }}:{{ .Values.prometheusExporterImage.tag }}
          imagePullPolicy: {{ .Values.prometheusExporterImage.pullPolicy }}
          command:
            - haproxy_exporter
            - --haproxy.scrape-uri=http://{{ .Release.Name }}-stats/stats;csv
          ports:
            - name: metrics
              containerPort: 9101
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics
          resources:
{{ toYaml .Values.metrics.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- end }}
