---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-stats
  labels:
    {{- include "haproxy-postgres.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.stats.type }}
  ports:
    - name: metrics
      port: 80
      targetPort: stats
      protocol: TCP
      {{- if (and (eq .Values.services.stats.type "NodePort") (not (empty .Values.services.stats.nodePort))) }}
      nodePort: {{ .Values.services.stats.nodePort }}
      {{- end }}
  selector:
    {{- include "haproxy-postgres.selector" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-master
  labels:
    {{- include "haproxy-postgres.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.master.type }}
  ports:
    - name: pgsql
      port: 5432
      targetPort: pgsql-master
      protocol: TCP
      {{- if (and (eq .Values.services.master.type "NodePort") (not (empty .Values.services.master.nodePort))) }}
      nodePort: {{ .Values.services.master.nodePort }}
      {{- end }}
  selector:
    {{- include "haproxy-postgres.selector" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-slave
  labels:
    {{- include "haproxy-postgres.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.slave.type }}
  ports:
    - name: pgsql
      port: 5432
      targetPort: pgsql-slave
      protocol: TCP
      {{- if (and (eq .Values.services.slave.type "NodePort") (not (empty .Values.services.slave.nodePort))) }}
      nodePort: {{ .Values.services.slave.nodePort }}
      {{- end }}
  selector:
    {{- include "haproxy-postgres.selector" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-all
  labels:
    {{- include "haproxy-postgres.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.all.type }}
  ports:
    - name: pgsql
      port: 5432
      targetPort: pgsql-all
      protocol: TCP
      {{- if (and (eq .Values.services.all.type "NodePort") (not (empty .Values.services.all.nodePort))) }}
      nodePort: {{ .Values.services.all.nodePort }}
      {{- end }}
  selector:
    {{- include "haproxy-postgres.selector" . | nindent 4 }}
