---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-stats
  labels:
{{ include "haproxy-postgres.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: stats
      protocol: TCP
  selector:
{{ include "haproxy-postgres.labels" . | indent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-master
  labels:
{{ include "haproxy-postgres.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: pgsql
      port: 5432
      targetPort: pgsql-master
      protocol: TCP
  selector:
{{ include "haproxy-postgres.labels" . | indent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-slave
  labels:
{{ include "haproxy-postgres.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: pgsql
      port: 5432
      targetPort: pgsql-slave
      protocol: TCP
  selector:
{{ include "haproxy-postgres.labels" . | indent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-all
  labels:
{{ include "haproxy-postgres.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: pgsql
      port: 5432
      targetPort: pgsql-all
      protocol: TCP
  selector:
{{ include "haproxy-postgres.labels" . | indent 4 }}
