image:
  repository: wrouesnel/postgres_exporter
  tag: v0.8.0
  pullPolicy: IfNotPresent

pg_stat_statements: true
version: "12"
username: postgres
password: pgpass
master: master:5432/postgres?sslmode=require
replicas:
  - replica0:5432/postgres?sslmode=require
  - replica1:5432/postgres?sslmode=require
  - replica2:5432/postgres?sslmode=require
