image:
  repository: wrouesnel/postgres_exporter
  tag: v0.8.0
  pullPolicy: IfNotPresent

pg_stat_statements: true
version: "12"
master:
  uri: master:5432/postgres?sslmode=require
  username: postgres
  password: pgpass
replicas:
  - uri: replica0:5432/postgres?sslmode=require
    username: postgres
    password: pgpassmaster
  - uri: replica1:5432/postgres?sslmode=require
    username: postgres
    password: pgpassreplica0
  - uri: replica2:5432/postgres?sslmode=require
    username: postgres
    password: pgpassreplica1
