---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "puppetboard.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "puppetboard.name" . }}
    helm.sh/chart: {{ include "puppetboard.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
stringData:
  autosign_psk: {{ .Values.autosign.psk | quote }}
