apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "common.fullname" . | quote }}
  labels:
{{ include "common.labels.standard" . | indent 4 }}
spec:
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: {{ .Values.nfs.reclaimName }}
    namespace: {{ .Values.nfs.reclaimNamespace }}
  capacity:
    storage: {{ .Values.nfs.capacity | quote }}
  accessModes:
  - ReadWriteMany
  nfs:
    path: {{ .Values.nfs.path | quote }}
    server: {{ .Values.nfs.server | quote }}
  persistentVolumeReclaimPolicy: {{ .Values.nfs.reclaimPolicy | quote }}
