# Git source definition to be build with a s2i image
source:
  uri: __GIT_URI__
  ref: __GIT_BRANCH__
  secretName: __GIT_SECRET__

build:
  # Caution, this input imageStream must exist.
  # As it can be used for multiple builds, first check if it exists.
  # Use the import-image chart if you need to import images
  #
  # commit: add commit builds and is for remote image updates management
  # commit:
  #   enabled: true
  # This imagestream will be triggered for changes.
  # You will find a .parent-images directory in your repo for change tracking.
  input:
    kind: ImageStreamTag
    namespace: __S2I_IS_NAMESPACE__
    name: __S2I_IS_NAME__:__S2I_IS_TAG__

  output:
    privateImage:
      repository: __PRIVATE_REPO_NAME__
      org: __PRIVATE_REPO_ORG__
      name: __PRIVATE_IMAGE_NAME__
      tag: __PRIVATE_IMAGE_TAG__
    imageStream:
      namespace: __IS_NAMESPACE__
      name: __IS_NAME__
      tag: __IS_TAG__
