apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: {{ include "infra-doc.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "infra-doc.name" . }}
    helm.sh/chart: {{ include "infra-doc.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "infra-doc.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "infra-doc.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: "{{ .Chart.Name }}"
        image: ' '
        ports:
        - containerPort: 8081
          procotol: TCP
  triggers:
    - type: "ImageChange"
      imageChangeParams:
        automatic: true
        from:
          kind: "ImageStream"
          name: "{{ .Chart.Name }}-nginx:latest"
        containerNames: [ "{{ .Chart.Name }}" ]
