---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "infra-doc.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "infra-doc.name" . }}
    helm.sh/chart: {{ include "infra-doc.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
stringData:
  WebHookSecretKey: {{ .Values.webhook.secret }}
  ssh-privatekey: |-
    {{ .Values.git.sshkey | nindent 4 }}
