apiVersion: v1
appVersion: "2.1"
description: backup interface for volumes attached to containers
home: https://github.com/camptocamp/bivac
icon: https://raw.githubusercontent.com/camptocamp/bivac/master/img/bivac_small.png
keywords:
- backup
- bivac
- restic
- volume
- kubernetes
- openshift
maintainers:
- email: info@camptocamp.com
  name: Camptocamp
name: bivac2
sources:
- https://github.com/camptocamp/bivac
version: 0.1.1
