image:
  repository: camptocamp/puppetserver
  tag: 'latest'
  pullPolicy: Always
service:
  type: 'ClusterIP'
  port: '8140'

# General
auth_conf: ''
ca_conf: ''
puppet_conf: ''
puppetdb_conf: ''
routes_yaml: ''

# CA
ca:
  key: ''
  crt: ''
  crl: ''
  autosign:
    script: ''
    psk: ''

# Hiera
gpg: ''
