---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lamphttpd.fullname" . }}-config
  labels:
{{ include "lamphttpd.labels" . | indent 4 }}
data:
  user.conf: |
{{ .Values.apache.user | indent 4 }}
  remoteips.conf: |+
{{ .Values.apache.remoteips | indent 4 }}
  probe.html: |
    OK
  probe.conf: |
      Alias /probe /var/www/html/probe.html
      <Directory "/etc/httpd/htdocs">
          Options Indexes FollowSymLinks
          AllowOverride All
          Order allow,deny
          Allow from all
          Require all granted
      </Directory>
  mode_status.conf: |
      ExtendedStatus on
      <Location /mod_status>
          SetHandler server-status
          Order deny,allow
          Deny from all
          Allow from 127.0.0.1 localhost
      </Location>