apiVersion: v1
kind: Service
metadata:
  name: {{ include "lamphttpd.fullname" . }}
  labels:
{{ include "lamphttpd.labels" . | indent 4 }}
    app: {{ include "lamphttpd.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: web
      port: {{ .Values.service.port | default "8080" }}
      targetPort: web
      protocol: TCP
{{- if .Values.extraServicePorts }}
{{ toYaml .Values.extraServicePorts | indent 4 }}
{{- end }}
    {{- if .Values.monitoring.enabled }}
    - port: {{ .Values.monitoring.portNumber | default 9117 }}
      targetPort: exporter
      protocol: TCP
      name: exporter
    {{- end }}      
  selector:
    app.kubernetes.io/name: {{ include "lamphttpd.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
