apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  generateName: prometheus-
  name: {{ include "subscription.fullname" . }}
  labels:
{{ include "subscription.labels" . | indent 4 }}
spec:
  source: {{ .Values.source }}
  name: {{ .Values.name }}
  startingCSV: {{ .Values.startingCSV }}
  channel: {{ .Values.channel }}
