apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: openshift-acme
  labels:
{{ include "common.labels.standard" . | indent 4 }}
spec:
  tags:
  - name: latest
    from:
      kind: DockerImage
      name: docker.io/tnozicka/openshift-acme:latest
    importPolicy:
      scheduled: true