apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ template "s3-exporter.fullname" . }}
  labels:
    {{- include "s3-exporter.selectorLabels" . | nindent 8 }}
spec:
  groups:
  - name: {{ template "s3-exporter.fullname" . }}-{{ .Release.Namespace }}
    rules:
      - alert: GitLabBackupSizeTooSmall
        expr: s3_last_modified_object_size_bytes < 1e+06
        for: 5m
        labels:
          {{- toYaml .Values.prometheusrules.labels | nindent 10 }}
        annotations:
          description: GitLab backup file '{{ "{{ $labels.file }}" }}' is too small
          summary: GitLab backup file '{{ "{{ $labels.file }}" }}' is too small
      - alert: GitLabLatestBackupAge
        expr: time()
          - s3_last_modified_object_date{namespace={{ quote .Release.Namespace }} }/ 1000 > 108000
        for: 5m
        labels:
          {{- toYaml .Values.prometheusrules.labels | nindent 10 }}
        annotations:
          description: The latest GitLab backup file '{{ "{{ $labels.file }}" }}' is more
            than 1 day old ({{ "{{ $value | humanizeDuration }}" }})
          summary: Latest GitLab backup file  '{{ "{{ $labels.file }}" }}' is more than 1 day
            old ({{ "{{ $value | humanizeDuration }}" }})
