apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ include "s3-exporter.fullname" . }}
  labels:
    app: {{ template "s3-exporter.name" . }}
    app.kubernetes.io/name: {{ include "s3-exporter.name" . }}
    helm.sh/chart: {{ include "s3-exporter.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    name:  s3-exporter
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:

  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "s3-exporter.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name:  s3-exporter
        release: {{ .Release.Name }}
        app.kubernetes.io/name: {{ include "s3-exporter.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image:  "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - containerPort: {{ .Values.service.port }}
            name: s3-exporter
            protocol: TCP
          volumeMounts:
          - mountPath: /config
            name: config-vol
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: config-vol
          configMap:
            name: {{ template "s3-exporter.fullname" . }}
            items:
              - key: config
                path: config.yml
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}stable
    {{- end }}
    {{- with .Values.tolerations }}stable
      tolerations:
        {{- toYaml . | nindent 8 }}stable
    {{- end }}
      restartPolicy: Always