{{ if .Values.servicemonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "s3-exporter.fullname" . }}
spec:
  endpoints:
  - port: {{ include "s3-exporter.fullname" . }}
    path: /metrics
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app:  {{ template "s3-exporter.fullname" . }}
      release: {{ .Release.Name }}
{{ end }}

