{{ if .Values.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pushprox.fullname" . }}-htpasswd
  labels:
{{ include "pushprox.labels" . | indent 4 }}
type: Opaque
data:
  auth: {{ .Values.htpasswd | b64enc }}
{{ end }}
