apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "prometheus-puppetdb-sd.fullname" $ }}
  labels:
    {{- include "prometheus-puppetdb-sd.labels" $ | nindent 4 }}
rules:
{{- if eq (default "" (index $.Values.prometheusPuppetdbSd.args "output.method")) "k8s-secret" }}
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["*"]
{{- end }}
