---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-r10k
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app: {{ template "name" . }}
data:
  r10k.yaml: |
    # The location to use for storing cached Git repos
    :cachedir: '/etc/puppetlabs/code/cache'

    # A list of git repositories to create
    :sources:
      :main:
        remote: '{{ .Values.remote }}'
        basedir: '/etc/puppetlabs/code/environments'
