---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app: {{ template "name" . }}
spec:
  replicas: 1
  strategy:
    resources: {}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: useroot
      containers:
        - name: r10k-webhook
          image: {{ .Values.image }}:{{ .Values.imageTag }}
          imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
          env:
{{- if .Values.githubToken }}
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}-ssh
                  key: githubToken
{{- end }}
            - name: RSA_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}-ssh
                  key: id_rsa
          readinessProbe:
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 9000
            timeoutSeconds: 1
          resources: {}
          volumeMounts:
            - mountPath: /etc/puppetlabs/code
              name: puppetcode
            - mountPath: /etc/puppetlabs/r10k
              name: config-volume-r10k
              readOnly: true
            - mountPath: /etc/webhook
              name: secret-volume-webhook
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: puppetcode
          persistentVolumeClaim:
            claimName: puppet-puppetserver-puppetcode
        - name: config-volume-r10k
          configMap:
            name: {{ template "fullname" . }}-r10k
        - name: secret-volume-webhook
          secret:
            secretName: {{ template "fullname" . }}-webhook
        - name: secret-volume-ssh
          secret:
            secretName: {{ template "fullname" . }}-ssh
            defaultMode: 0600
