apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pghoard.fullname" . }}
  labels:
    app: {{ include "pghoard.name" . }}
    chart: {{ include "pghoard.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  pghoard.json: |-
{{ .Values.pghoard_json | indent 4 }}
