apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pghoard.fullname" . }}
  labels:
{{ include "pghoard.labels" . | indent 4 }}
data:
  pghoard.json: |-
{{ .Values.pghoard_json | indent 4 }}
