---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: {{ include "pghoard.fullname" . }}
  labels:
    app: {{ include "pghoard.name" . }}
    chart: {{ include "pghoard.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  strategy:
    resources: {}
  template:
    metadata:
      labels:
        app: {{ include "pghoard.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - image: ' '
          command: ["pghoard"]
          args: ["--config", "/etc/pghoard/pghoard.json"]
          name: pghoard
          env:
            - name: PGPASSFILE
              value: /home/postgres/.pgpass
          ports:
            - name: http
              containerPort: 16000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          resources: {}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/pghoard
            - name: pghoard
              mountPath: /var/lib/pghoard
      restartPolicy: Always
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "pghoard.fullname" . }}
        - name: pghoard
          persistentVolumeClaim:
            claimName: {{ include "pghoard.fullname" . }}
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - pghoard
        from:
          kind: ImageStreamTag
          name: {{ include "pghoard.fullname" . }}:{{ .Values.imageTag }}
      type: ImageChange
