---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ include "pghoard.fullname" . }}
  labels:
    app: {{ include "pghoard.name" . }}
    chart: {{ include "pghoard.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  tags:
    - name: "{{ .Values.image.tag }}"
      from:
        kind: DockerImage
        name: {{ .Values.image.repository }}:{{ .Values.image.tag }}
      referencePolicy:
        type: Source
