---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ template "fullname" . }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app: {{ template "name" . }}
spec:
  tags:
    - name: "{{ .Values.imageTag }}"
      from:
        kind: DockerImage
        name: {{ .Values.image }}:{{ .Values.imageTag }}
      referencePolicy:
        type: Source
