{{- if .Values.persistentVolume.enabled -}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pghoard.fullname" . }}
  labels:
    app: {{ include "pghoard.name" . }}
    chart: {{ include "pghoard.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
{{ toYaml .Values.persistentVolume.accessModes | indent 4 }}
{{- if .Values.persistentVolume.storageClass }}
{{- if (eq "-" .Values.persistentVolume.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistentVolume.storageClass }}"
{{- end -}}
{{- end -}}
  resources:
    requests:
      storage: {{ .Values.persistentVolume.size | quote }}
{{- end -}}
