apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "pghoard.fullname" . }}
  labels:
{{ include "pghoard.labels" . | indent 4 }}
stringData:
  pghoard.json: |-
{{ .Values.pghoard_json | indent 4 }}
