# Default values for prometheus-puppetdb-sd.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: camptocamp/prometheus-puppetdb-sd
  tag: 0.11.0
  pullPolicy: IfNotPresent

prometheusPuppetdbSd:
  init:
    psk: ''
    puppetserver: puppetserver.puppet.svc.cluster.local
    autosign:
      resources: {}
  args:
    puppetdb.url: "https://puppetdb.camptocamp.com"
    prometheus.proxy-url: "http://pushprox:8080"
    output.method: k8s-secret
    output.k8s-secret.secret-name: prometheus-puppetdb-sd-output
    output.k8s-secret.secret-key: puppetdb-sd.yml

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
