---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app: {{ template "name" . }}
spec:
  replicas: 1
  strategy:
    resources: {}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: useroot
      containers:
        - env:
            - name: PUPPETBOARD_OVERVIEW_FILTER
              value: {{ .Values.overviewFilter }}
            - name: PUPPETBOARD_INVENTORY_FACTS
              value: {{ .Values.inventoryFacts | quote }}
            - name: PUPPETBOARD_SETTINGS
              value: /app/settings.py
          name: puppetboard
          image: {{ .Values.image }}:{{ .Values.imageTag }}
          imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
          resources: {}
      restartPolicy: Always
