apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ template "tirsias.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ template "tirsias.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups: ['']
    resources:
      - serviceaccounts
      - secrets
    verbs:
      - get
  - apiGroups: ['monitoring.coreos.com']
    resources:
      - prometheuses
      - alertmanagers
    verbs:
      - list
      - get
      - watch
---
apiVersion: v1
kind: ServiceAccount
{{ if .Values.image.pullSecret -}}
imagePullSecrets:
  - name: {{ .Values.image.pullSecret }}
{{- end }}
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ template "tirsias.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
