{{ $root := . }}
apiVersion: v1
items:
{{- range $key, $value := .Values.projects }}
  {{- if $value.deployTiller }}
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    labels:
{{ include "common.labels.standard" $root | indent 6 }}
    name: "tiller-deploy"
    namespace: {{ $key }}
  {{- end }}
{{- end }}
kind: List