{{ $root := . }}
apiVersion: v1
items:
{{- range $key, $value := .Values.projects }}
  {{- if $value.tiller }}
- kind: RoleBinding
  apiVersion: authorization.openshift.io/v1
  metadata:
    labels:
{{ include "common.labels.standard" $root | indent 6 }}
    name: tiller
    namespace: {{ $key }}
  roleRef:
    name: tiller
    namespace: {{ $key }}
  subjects:
  - kind: ServiceAccount
    name: tiller
    namespace: {{ $key }}
  spec:
    finalizers:
    - openshift.io/origin
    - kubernetes
  {{- end }}
{{- end }}
kind: List

