{{ $root := . }}
apiVersion: v1
items:
{{- range $key, $value := .Values.projects }}
  {{- range $helmAccess := $value.helmAccess }}
- kind: RoleBinding
  apiVersion: authorization.openshift.io/v1
  metadata:
    labels:
{{ include "common.labels.standard" $root | indent 6 }}
    name: helm-user-binding
    namespace: {{ $key }}
  roleRef:
    name: helm-user
    namespace: {{ $key }}
  subjects:
  - kind: ServiceAccount
    name: {{ $helmAccess.ServiceAccountName }}
    namespace: {{ $helmAccess.ServiceAccountNameSpace }}
  {{- end }}
{{- end }}
kind: List

