
name: my_secret_name
type: kubernetes.io/dockerconfigjson
data:
- key: .dockerconfigjson
  value: |
    {
      "auths": {
        "mydocker.registry.com": {
          "auth": "my_auth_token",
          "email": "my_email"
        }
      }
    }
