
name: my_secret_name
type: kubernetes.io/dockerconfigjson
# annotations:
#   build.openshift.io/source-secret-match-uri-1: ssh://mygitlab.example.com:1234/*
data:
- key: .dockerconfigjson
  value: |
    {
      "auths": {
        "mydocker.registry.com": {
          "auth": "my_auth_token",
          "email": "my_email"
        }
      }
    }
