---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: {{ template "conplicity.fullname" . }}
  labels:
    app: {{ template "conplicity.name" . }}
    chart: {{ template "conplicity.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "conplicity.name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ template "conplicity.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CONPLICITY_ENGINE
              value: restic
            - name: CONPLICITY_ORCHESTRATOR
              value: kubernetes
{{ toYaml .Values.envVars | indent 12 }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
  triggers:
    - type: ConfigChange
