{{ $root := . }}
{{- range $key, $value := .Values.projects }}
{{-   if and $root.Values.anyUid $root.Values.anyUid.bindToSccName }}
---
apiVersion: authorization.openshift.io/v1
kind: Role
metadata:
  labels:
{{      include "common.labels.standard" $root | indent 4 }}
  namespace: {{ $key }}
  name: anyuid
rules:
- apiGroups: ["security.openshift.io"]
  resources: ["securitycontextconstraints"]
  resourceNames: ["{{ $root.Values.anyUid.bindToSccName }}"]
  verbs: ["use"]

---
kind: RoleBinding
apiVersion: authorization.openshift.io/v1
metadata:
  labels:
{{      include "common.labels.standard" $root | indent 4 }}
  name: anyuid
  namespace: {{ $key }}
roleRef:
  name: anyuid
  namespace: {{ $key }}
subjects:
- kind: ServiceAccount
  name: {{ $root.Values.anyUid.ServiceAccountName }}
  namespace: {{ $key }}
userNames:
- system:serviceaccount:{{ $key }}:{{ $root.Values.anyUid.ServiceAccountName }}
{{-     end }}
{{-   end }}
