{{ $root := . }}
{{- range $key, $value := .Values.projects }}
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
{{-   if $value.nodeSelector }}
    openshift.io/node-selector: {{ $value.nodeSelector | quote }}
{{-   end }}
    openshift.io/description: |
{{ $value.description | indent 6 }}
    openshift.io/display-name: {{ $key }}
  labels:
{{    include "common.labels.standard" $root | indent 4 }}
  name: {{ $key }}
{{- end }}
