apiVersion: v1
kind: Service
metadata:
  name: {{ template "openshift-logstash.fullname" . }}
  labels:
    app: {{ template "openshift-logstash.name" . }}
    chart: {{ template "openshift-logstash.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{ if eq .Values.service.type "NodePort" }}
       {{- range .Values.UDPports }}
      - nodePort:  {{ .listenport }}
        port: {{ .portnum }}
        targetPort: {{ .portnum }}
        protocol: UDP
        name: {{ .name | quote }}
      {{- end }}
    {{ else }}
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
     {{ end  }}
  selector:
    app: {{ template "openshift-logstash.name" . }}
    release: {{ .Release.Name }}
