# Default values for openshift-jenkins.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# Default values for openshift-jenkins.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# The name of the OpenShift Service exposed for the Jenkins container.
jenkins_service_name: jenkins

# The name of the service used for master/slave communication.
jnlp_service_name: jenkins-jnlp

# Whether to enable OAuth OpenShift integration. If false, the static
# account 'admin' will be initialized with the password 'password'.
enable_oauth: "true"

# Maximum amount of memory the container can use.
memory_limit: 1Gi

# Volume space available for data, e.g. 512Mi, 2Gi.
volume_capacity: 1Gi

# The OpenShift Namespace where the Jenkins ImageStream resides.
namespace: cicd

# Name of the ImageStreamTag to be used for the Jenkins image.
jenkins_image_stream_tag: "jenkins-custom:latest"

# When running this image with an OpenShift persistent volume for the Jenkins
# config directory, the transfer of configuration from the image to the persistent
# volume is only done the first startup of the image as the persistent volume is
# assigned by the persistent volume claim creation. If you create a custom image
# that extends this image and updates configuration in the custom image after the
# initial startup, by default it will not be copied over, unless you set this 
# environment variable to some non-empty value.
#
# overridePvConfigWithImageConfig: true

# Comma-separated list of additional plugins to install on startup. The format of each plugin spec is plugin-id:version (as in plugins.txt)
#install_plugins: gitlab-plugin:1.5.3

javaGcOpts: "-XX:+UseParallelGC -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MaxMetaspaceSize=2g"

sshSecretName: my-ssh-private-key-secret
sshPrivateKey: <ssh_private_key>

# Custom image
JenkinsCustom:
  enable: true
  gitSource: git@myGitServer:myGitGroup/myGitProject.git
  contextDir: openshift/build/jenkins-custom

gitlabConnection:
  name: 'Gitlab'
  url: 'https://myGitServer/'
  apiTokenId: 'gitlab-token'
  apiToken: '<myGitlabToken>'
  ignoreCertificateErrors: false
  connectionTimeout: 10
  readTimeout: 10

jenkins_slaves:
  slave1:
    repository:
      url: git@myGitServer:myGitGroup/jenkinsSlavesProject.git
      ref: master
      context_dir: slave1
  slave2:
    repository:
      url: git@myGitServer:myGitGroup/jenkinsSlavesProject.git
      ref: master
      context_dir: slave2
