# Default values for s3-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ribbybibby/s3-exporter
  tag: v0.5.0
  pullPolicy: IfNotPresent

service:
  port: 9340
  type: ClusterIP

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 300m
    memory: 256M
  requests:
    cpu: 100m
    memory: 50M

nodeSelector: {}

tolerations: []

affinity: {}

autoscaling:
  enabled: false

ingress:
  enabled: false

serviceAccount:
  create: false

servicemonitor:
  enabled: false

prometheusrules:
  oldestfiledays: 7
  labels:
    severity: "warning"
    line: "prod"

s3:
  accessKey: "S3-ACCESS-KEY"
  secretKey: "S3-SECRET-KEY"
exporterFlags:
  - '--log.level=debug'

podAnnotations: []

imagePullSecrets: []

# Inject the dashboard for this exporter
dashboards:
  enabled: false
  job: s3-exporter # The name of the job label in the prometheus metric
#  namespace: app Which namesapce the probes are deployed

