# Default values for s3-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ribbybibby/s3-exporter
  tag: v0.5.0
  pullPolicy: IfNotPresent

service:
  port: 9340
  type: ClusterIP

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 300m
    memory: 256M
  requests:
    cpu: 100m
    memory: 50M

nodeSelector: {}

tolerations: []

affinity: {}

autoscaling:
  enabled: false

ingress:
  enabled: false

serviceAccount:
  create: false

servicemonitor:
  enabled: false

prometheusrules:
  oldestfiledays: 7
  labels:
    severity: "warning"
    line: "prod"

s3:
  accessKeyId: "S3-ACCESS-KEY"
  secretAccessKey: "S3-SECRET-KEY"
# region: us-east-1
exporterFlags:
  - '--log.level=debug'

podAnnotations: []

imagePullSecrets: []

dashboards:
  enabled: true
  job: gitlab-s3-exporter
  namespace: gitlab

