# Default values for ldap-search-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: docker.io/camptocamp/ldap-search-exporter
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: nginx
  type: ClusterIP
  externalPort: 9117
  internalPort: 9117

ldap:
  address: TO_BE_DEFINED
  basedn: TO_BE_DEFINED
  queries: TO_BE_DEFINED
  queryInterval: 120
