---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: {{ include "g10k-webhook-build.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "g10k-webhook-build.name" . }}
    helm.sh/chart: {{ include "g10k-webhook-build.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  output:
    to:
      kind: ImageStreamTag
      name: {{ include "g10k-webhook-build.fullname" . }}:latest
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/camptocamp/docker-g10k-webhook.git
      ref: master
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: {{ include "g10k-webhook-build.fullname" . }}-debian:stretch
      forcePull: true
    type: Docker
  triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
