apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "getconfig.fullname" . }}
  labels:
    {{- include "getconfig.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: {{ include "getconfig.fullname" . }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ include "getconfig.fullname" $ }}
              servicePort: 80
