{{ $root := . }}
{{- range $role := .Values.roles }}
---
apiVersion: authorization.openshift.io/v1
kind: Role
metadata:
  name: {{ $role.name }}
  namespace: {{ $root.Release.Namespace }}
# {{-   with $role.namespace }}
#   namespace: {{ . }}
# {{-   end }}
  labels:
{{ include "common.labels.standard" $root | indent 4 }}
{{-   with $role.rules }}
rules:
{{   toYaml . }}
{{-   end }}
{{- end }}