{{ $root := . }}
{{- range $serviceAccount := .Values.serviceAccounts }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $serviceAccount.name }}
  labels:
{{ include "common.labels.standard" $root | indent 4 }}
{{- end }}
