{{ $root := . }}
{{- range $serviceAccount := .Values.serviceAccounts }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $serviceAccount.name }}
{{-   with $serviceAccount.namespace }}
  namespace: {{ . }}
{{-   end }}
  labels:
{{ include "common.labels.standard" $root | indent 4 }}
{{-   with $serviceAccount.secrets }}
secrets:
{{   toYaml . }}
{{-   end }}
{{- end }}
