{{- if .Values.route.enabled -}}
{{- $serviceName := include "kibana.fullname" . -}}
{{- $servicePort := .Values.service.externalPort -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: {{ template "kibana.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "kibana.fullname" . }}
  annotations:
    {{- range $key, $value := .Values.route.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  {{- if .Values.route.host }}
  host: {{ .Values.route.host }}
  {{- end }}
  to:
    kind: Service
    name: {{ $serviceName }}
  {{- if .Values.route.tls }}
  tls:
{{ toYaml .Values.route.tls | indent 4 }}
  {{- end -}}
{{- end -}}
