{{- if .Values.ssl.enabled }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "kibana.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "kibana.fullname" . }}-ssl
data:
  certificate.pem: {{ .Values.ssl.certificate }}
  privkey.pem: {{ .Values.ssl.privkey }}
{{- end }}
