replicaCount: 1

## Override the deployment namespace
##
namespaceOverride: ""

image:
  repository: php
  tag: 7.3-apache
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

monitoring:
  enabled: false
  image:
    repository: lusotycoon/apache-exporter
    tag: v0.8.0
    pullPolicy: IfNotPresent
  portNumber: '9117'

build:
  dockerfile: |
    FROM php:7.4-apache
    RUN apt-get update && \
        apt-get install -y libmcrypt-dev zlib1g-dev libfreetype6-dev libjpeg62-turbo-dev libpng-dev libtidy-dev libldap2-dev libxml2-dev && \
        apt-get clean && \
        pecl install mcrypt && \
        docker-php-ext-configure gd --with-freetype --with-jpeg && \
        docker-php-ext-install bcmath gd ldap mysqli pdo pdo_mysql soap tidy && \
        docker-php-ext-enable mcrypt
    RUN /usr/sbin/a2disconf other-vhosts-access-log

apache:
  config: ""

php:
  config: |
    engine = On
    short_open_tag = Off
    precision = 14
    output_buffering = 4096
    zlib.output_compression = Off
    implicit_flush = Off
    unserialize_callback_func =
    serialize_precision = -1
    disable_functions =
    disable_classes =
    zend.enable_gc = On
    zend.exception_ignore_args = On
    expose_php = On
    max_execution_time = 30
    max_input_time = 60
    memory_limit = 128M
    display_errors = Off
    display_startup_errors = Off
    log_errors = On
    log_errors_max_len = 1024
    ignore_repeated_errors = Off
    ignore_repeated_source = Off
    report_memleaks = On
    variables_order = "GPCS"
    request_order = "GP"
    register_argc_argv = Off
    auto_globals_jit = On
    post_max_size = 8M
    auto_prepend_file =
    auto_append_file =
    default_mimetype = "text/html"
    default_charset = "UTF-8"
    doc_root =
    user_dir =
    enable_dl = Off
    file_uploads = On
    upload_max_filesize = 16M
    max_file_uploads = 20
    allow_url_fopen = On
    allow_url_include = Off
    default_socket_timeout = 60
    cli_server.color = On
    pdo_mysql.default_socket=
    smtp_port = 25
    mail.add_x_header = Off
    odbc.allow_persistent = On
    odbc.check_persistent = On
    odbc.max_persistent = -1
    odbc.max_links = -1
    odbc.defaultlrl = 4096
    odbc.defaultbinmode = 1
    mysqli.max_persistent = -1
    mysqli.allow_persistent = On
    mysqli.max_links = -1
    mysqli.default_port = 3306
    mysqli.default_socket =
    mysqli.default_host =
    mysqli.default_user =
    mysqli.default_pw =
    mysqli.reconnect = Off
    mysqlnd.collect_statistics = On
    mysqlnd.collect_memory_statistics = Off
    session.save_handler = files
    session.use_strict_mode = 0
    session.use_cookies = 1
    session.use_only_cookies = 1
    session.name = PHPSESSID
    session.auto_start = 0
    session.cookie_lifetime = 0
    session.cookie_path = /
    session.cookie_domain =
    session.cookie_httponly =
    session.cookie_samesite =
    session.serialize_handler = php
    session.gc_probability = 1
    session.gc_divisor = 1000
    session.gc_maxlifetime = 1440
    session.referer_check =
    session.cache_limiter = nocache
    session.cache_expire = 180
    session.use_trans_sid = 0
    session.sid_length = 26
    session.trans_sid_tags = "a=href,area=href,frame=src,form="
    session.sid_bits_per_character = 5
    zend.assertions = -1
    tidy.clean_output = Off
    soap.wsdl_cache_enabled=1
    soap.wsdl_cache_dir="/tmp"
    soap.wsdl_cache_ttl=86400
    soap.wsdl_cache_limit = 5


service:
  type: LoadBalancer
  port: 8080

storage:
  pvName: ""

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
