---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: {{ template "fullname" . }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app: {{ template "name" . }}
spec:
  output:
    to:
      kind: ImageStreamTag
      name: {{ template "fullname" . }}:5.1.5-0.2
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/camptocamp/docker-puppetserver.git
      ref: 5.1.5-0.2
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: {{ template "fullname" . }}-ubuntu:xenial
      forcePull: true
    type: Docker
  triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
