---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: {{ template "fullname" . }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app: {{ template "name" . }}
spec:
  replicas: 1
  strategy:
    resources: {}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: useroot
      containers:
        - env:
            - name: AUTOSIGN_PSK
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: autosign-psk
{{- if .Values.caCrt }}
            - name: CA_CRT
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: ca-crt
{{- end }}
{{- if .Values.caKey }}
            - name: CA_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: ca-key
{{- end }}
            - name: DNS_ALT_NAMES
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: dns-alt-names
{{- if .Values.gpgKey }}
            - name: GPG_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: gpg-key
{{- end }}
            - name: JAVA_ARGS
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: java_args
          image: ' '
          name: puppet
          resources: {}
          volumeMounts:
            - name: puppetcode
              mountPath: /etc/puppetlabs/code/environments
            - name: puppetca
              mountPath: /etc/puppetlabs/puppet/ssl/ca
            - name: r10kcache
              mountPath: /opt/puppetlabs/r10k/cache
      restartPolicy: Always
      volumes:
        - name: puppetcode
          persistentVolumeClaim:
            claimName: {{ template "fullname" . }}-puppetcode
        - name: puppetca
          persistentVolumeClaim:
            claimName: {{ template "fullname" . }}-puppetca
        - name: r10kcache
          persistentVolumeClaim:
            claimName: {{ template "fullname" . }}-r10kcache
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - puppet
        from:
          kind: ImageStreamTag
          name: {{ template "fullname" . }}:5.1.5-0.2
      type: ImageChange
