---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ template "fullname" . }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app: {{ template "name" . }}
spec:
  lookupPolicy:
    local: false
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ template "fullname" . }}-ubuntu
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app: {{ template "name" . }}
spec:
  lookupPolicy:
    local: false
  tags:
    - name: xenial
      from:
        kind: DockerImage
        name: ubuntu:xenial
      referencePolicy:
        type: Source
