---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
stringData:
  autosign-psk: {{ .Values.autosignPsk }}
{{- if .Values.caCrt }}
  ca-crt: |
{{ .Values.caCrt | indent 4 }}
{{- end }}
{{- if .Values.caKey }}
  ca-key: |
{{ .Values.caKey | indent 4 }}
{{- end }}
{{- if .Values.gpgKey }}
  gpg-key: |
{{ .Values.gpgKey | indent 4 }}
{{- end }}
