---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app: {{ template "name" . }}
spec:
  ports:
    - name: puppet
      port: 8140
      protocol: TCP
      targetPort: 8140
  selector:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
