---
# required labels we have on every metric
sre_team: sret2
line: prod

# Below, generic overrides to upstream logstash chart. You can still
# over-override these or others from elastic/logstash in your local
# values.yaml
logstash:
  podSecurityContext:
    fsGroup: 1000380000
    runAsUser: 1000380000

  securityContext:
    runAsUser: 1000380000

  secretMounts:
    - name: kafka-ssl
      secretName: kafka-ssl
      path: /etc/logstash/kafka-ssl

  logstashPipeline:
    logstash.conf: |
      input {}
      output {}

  service:
    type: ClusterIP
    ports:
      - name: prometheus-exporter
        port: 9198
        protocol: TCP
        targetPort: 9198

  extraContainers: |
    - name: prometheus-exporter
      image: docker.io/sequra/logstash_exporter:v0.1.3
      resources:
        limits:
          memory: "256M"
        requests:
          memory: "16M"
          cpu: "10m"

# Ditto, for upstream elasticsearch-curator chart.
elasticsearch-curator:
  securityContext:
    runAsUser: 1000380000
  cronjob:
    failedJobsHistoryLimit: 2
    successfulJobsHistoryLimit: 3

  configMaps:
    config_yml: |-
      ---
      client:
        hosts:
          - elasticsearch.logs.camptocamp.com
        port: 443
        use_ssl: True
        http_auth: ${CURATOR_HTTP_AUTH}
