---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "puppet-catalog-diff-viewer.fullname" . }}-data
  labels:
    app.kubernetes.io/name: {{ include "puppet-catalog-diff-viewer.name" . }}
    helm.sh/chart: {{ include "puppet-catalog-diff-viewer.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  accessModes:
    - {{ .Values.persistence.data.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
{{- if .Values.persistence.data.storageClass }}
{{- if (eq "-" .Values.persistence.data.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.data.storageClass }}"
{{- end }}
{{- end }}
{{- if .Values.persistence.data.volumeName }}
  volumeName: "{{ .Values.persistence.data.volumeName }}"
{{- end }}
