apiVersion: v1
kind: Service
metadata:
  name: {{ include "puppet-catalog-diff-viewer.fullname" . }}
  labels:
{{ include "puppet-catalog-diff-viewer.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "puppet-catalog-diff-viewer.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
